name: maat_kiosk
description: Gym Kiosk application for class check-ins
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/
    - assets/images/
  
  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist/Geist-Regular.ttf
        - asset: assets/fonts/Geist/Geist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Geist/Geist-Medium.ttf
          weight: 500